function out1 = rho_f(in1,t)
%RHO_F
%    OUT1 = RHO_F(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Oct-2024 21:31:48

x1 = in1(1,:);
x2 = in1(2,:);
out1 = 1.0./((cos(x1-pi./2.0+atan2(sqrt(-((sin(t./2.0)+4.0./5.0).^2./2.0+(cos(t./2.0)+3.0./5.0).^2./2.0-1.0).^2+1.0),(sin(t./2.0)+4.0./5.0).^2./2.0+(cos(t./2.0)+3.0./5.0).^2./2.0)-angle(cos(t./2.0).*-1i+sin(t./2.0)+8.0e-1-6.0e-1i))-1.0).^2+(cos(x2-conj(acos((sin(t./2.0)+4.0./5.0).^2./2.0+(cos(t./2.0)+3.0./5.0).^2./2.0-1.0)))-1.0).^2).^(1.0./1.0e+1);
end
