function out1 = rho_f(in1,t)
%RHO_F
%    OUT1 = RHO_F(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Sep-2024 22:48:39

x1 = in1(1,:);
x2 = in1(2,:);
out1 = 1.0./((cos(x2-conj(acos((cos(t)+3.0./5.0).^2./2.0+(sin(t)+4.0./5.0).^2./2.0-1.0)))-1.0).^2+(cos(x1-pi./2.0-angle(cos(t).*-1i+sin(t)+8.0e-1-6.0e-1i)+atan2(sqrt(-((cos(t)+3.0./5.0).^2./2.0+(sin(t)+4.0./5.0).^2./2.0-1.0).^2+1.0),(cos(t)+3.0./5.0).^2./2.0+(sin(t)+4.0./5.0).^2./2.0))-1.0).^2).^(1.0./1.0e+1);
end
