function out1 = rho_f(in1,t)
%RHO_F
%    OUT1 = RHO_F(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Sep-2024 12:28:06

x1 = in1(1,:);
x2 = in1(2,:);
out1 = 1.0./((cos(x2-conj(acos((sin(exp(-5.0./t)).*3.0-1.0).^2./2.0-1.0./2.0)))-1.0).^2+(cos(x1-pi./2.0+atan2(sqrt(-((sin(exp(-5.0./t)).*3.0-1.0).^2./2.0-1.0./2.0).^2+1.0),(sin(exp(-5.0./t)).*3.0-1.0).^2./2.0+1.0./2.0)-angle(sin(exp(-5.0./t)).*3.0+-1.0-1i))-1.0).^2).^(1.0./1.0e+1);
end
