function time_varying_goal = x_ref_f(t)
%X_REF_F
%    TIME_VARYING_GOAL = X_REF_F(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Sep-2024 12:27:56

time_varying_goal = [sin(exp(-5.0./t)).*3.0-1.0,-1.0];
end
