function time_varying_goal = x_ref_f(t)
%X_REF_F
%    TIME_VARYING_GOAL = X_REF_F(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Sep-2024 22:34:06

time_varying_goal = [sin(t)+4.0./5.0,-cos(t)-3.0./5.0];
end
