function out1 = xd_f(t)
%XD_F
%    OUT1 = XD_F(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Sep-2024 12:28:05

out1 = [pi./2.0-atan2(sqrt(-((sin(exp(-5.0./t)).*3.0-1.0).^2./2.0-1.0./2.0).^2+1.0),(sin(exp(-5.0./t)).*3.0-1.0).^2./2.0+1.0./2.0)+angle(sin(exp(-5.0./t)).*3.0+-1.0-1i),acos((sin(exp(-5.0./t)).*3.0-1.0).^2./2.0-1.0./2.0)];
end
