function out1 = xd_f(t)
%XD_F
%    OUT1 = XD_F(T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    19-Sep-2024 15:49:20

out1 = [pi./2.0+angle(cos(t).*-1i+sin(t)+8.0e-1-6.0e-1i)-atan2(sqrt(-((cos(t)+3.0./5.0).^2./2.0+(sin(t)+4.0./5.0).^2./2.0-1.0).^2+1.0),(cos(t)+3.0./5.0).^2./2.0+(sin(t)+4.0./5.0).^2./2.0),acos((cos(t)+3.0./5.0).^2./2.0+(sin(t)+4.0./5.0).^2./2.0-1.0)];
