function out1 = xd_f(t)
%XD_F
%    OUT1 = XD_F(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    20-Sep-2024 15:25:41

out1 = [pi./2.0-atan2(sqrt(-((sin(t./2.0)+4.0./5.0).^2./2.0+(cos(t./2.0)+3.0./5.0).^2./2.0-1.0).^2+1.0),(sin(t./2.0)+4.0./5.0).^2./2.0+(cos(t./2.0)+3.0./5.0).^2./2.0)+angle(cos(t./2.0).*-1i+sin(t./2.0)+8.0e-1-6.0e-1i),acos((sin(t./2.0)+4.0./5.0).^2./2.0+(cos(t./2.0)+3.0./5.0).^2./2.0-1.0)];
end
