function out1 = jac_xd_f(t)
%JAC_XD_F
%    OUT1 = JAC_XD_F(T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    17-Aug-2024 20:40:09

out1 = [3.0./5.0e+1;-3.0./5.0e+1];
