function out1 = xd_f(t)
%XD_F
%    OUT1 = XD_F(T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    17-Aug-2024 20:40:08

out1 = [t.*(3.0./5.0e+1)-4.0./5.0;t.*(-3.0./5.0e+1)+6.0./5.0];
